// <auto-generated />
using System;
using Master.Database.Management.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Master.Database.Management.DataLayer.Migrations
{
    [DbContext(typeof(MdmContext))]
    partial class MdmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("FixCategory");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedTimestampUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedTimestampUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FixCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FixTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LastAccessedTimestampUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("SystemCostEstimate")
                        .HasColumnType("float");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UpdatedTimestampUtc")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FixCategoryId");

                    b.HasIndex("FixTypeId");

                    b.ToTable("FixTemplate");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplateTag", b =>
                {
                    b.Property<Guid>("FixTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("DeletedTimestampUtc")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("FixTemplateId", "TagName");

                    b.ToTable("FixTemplateTag");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateFieldValue", b =>
                {
                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("FieldId", "Value");

                    b.ToTable("FixTemplateFieldValue");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateSectionField", b =>
                {
                    b.Property<Guid>("FixTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DeletedTimestampUtc")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("FixTemplateId", "SectionId", "FieldId");

                    b.HasIndex("SectionId")
                        .IsUnique();

                    b.ToTable("FixTemplateSectionField");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Segments.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FixTemplateSectionFieldFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FixTemplateSectionFieldFixTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FixTemplateSectionFieldSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("FixTemplateSectionFieldFixTemplateId", "FixTemplateSectionFieldSectionId", "FixTemplateSectionFieldFieldId");

                    b.ToTable("FixTemplateField");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Segments.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("FixTemplateSection");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("FixType");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplate", b =>
                {
                    b.HasOne("Master.Database.Management.DataLayer.Models.FixCategory", "FixCategory")
                        .WithMany("FixTemplates")
                        .HasForeignKey("FixCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Master.Database.Management.DataLayer.Models.FixType", "FixType")
                        .WithMany("FixTemplates")
                        .HasForeignKey("FixTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FixCategory");

                    b.Navigation("FixType");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplateTag", b =>
                {
                    b.HasOne("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplate", "FixTemplate")
                        .WithMany("FixTemplateTags")
                        .HasForeignKey("FixTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixTemplate");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateFieldValue", b =>
                {
                    b.HasOne("Master.Database.Management.DataLayer.Models.FixTemplates.Segments.Field", "Field")
                        .WithMany("FixTemplateFieldValues")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateSectionField", b =>
                {
                    b.HasOne("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplate", "FixTemplate")
                        .WithMany("FixTemplateSectionFields")
                        .HasForeignKey("FixTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Master.Database.Management.DataLayer.Models.FixTemplates.Segments.Section", "Section")
                        .WithOne()
                        .HasForeignKey("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateSectionField", "SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixTemplate");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Segments.Field", b =>
                {
                    b.HasOne("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateSectionField", null)
                        .WithMany("Fields")
                        .HasForeignKey("FixTemplateSectionFieldFixTemplateId", "FixTemplateSectionFieldSectionId", "FixTemplateSectionFieldFieldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixCategory", b =>
                {
                    b.Navigation("FixTemplates");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.FixTemplate", b =>
                {
                    b.Navigation("FixTemplateSectionFields");

                    b.Navigation("FixTemplateTags");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Sections.FixTemplateSectionField", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixTemplates.Segments.Field", b =>
                {
                    b.Navigation("FixTemplateFieldValues");
                });

            modelBuilder.Entity("Master.Database.Management.DataLayer.Models.FixType", b =>
                {
                    b.Navigation("FixTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
